segment and sentry integration
fylein/fyle-qbo-app pull request #102
Opened 2021-08-20 12:15 UTC by labhvam5

2021-08-21 07:22 UTC, abhishek1234321 requested changes

2021-08-21 07:22 UTC, abhishek1234321 commented on src/main.ts
> +  dsn: 'https://2c8ecc063c1b45ca89bc77e58a30e098@o966029.ingest.sentry.io/5916901',
this should come from ENV variables

2021-08-21 07:22 UTC, abhishek1234321 commented on src/main.ts
> +      tracingOrigins: ['localhost', 'https://yourserver.io/api'],
this needs fixing no? read the documentation

2021-08-21 07:22 UTC, abhishek1234321 commented on src/main.ts
> +  tracesSampleRate: 1.0,
keep this to 0.5 for now, read about what this is, and how is it used and how can it help us

also talk to Chethan if need be

2021-08-21 07:22 UTC, abhishek1234321 commented on src/app/qbo/qbo.component.html
> +        <button type="button" mat-menu-item [routerLink]="['../auth/logout']" (click)="signOutEvent()">
`onSignOut`

2021-08-21 07:22 UTC, abhishek1234321 commented on src/app/qbo/qbo.component.ts
> +  signOutEvent() {
`onSignOut`

2021-08-21 07:22 UTC, abhishek1234321 commented on src/app/qbo/qbo.component.ts
> +    that.setIdentityOfUser(that.user.employee_email);
`setUserIdentity`

2021-08-21 07:22 UTC, abhishek1234321 commented on src/app/qbo/qbo.component.ts
> +  setIdentityOfUser(email) {
`setUserIdentity`

2021-08-21 07:22 UTC, abhishek1234321 commented on src/app/qbo/qbo.component.ts
> +  setIdentityOfUser(email) {
`email: string`

2021-08-21 07:22 UTC, abhishek1234321 commented on src/app/qbo/qbo.component.ts
> +    that.trackingService.onSignin(email, {});
`onSignIn`

2021-08-21 07:22 UTC, abhishek1234321 commented on src/index.html
> +  <script type="text/javascript">
Segment, Sentry and Hotjar stuff, should be 3 different PRs, that way we can merge and release independently 

also, smaller PRs always gets reviewed faster

2021-08-21 07:22 UTC, abhishek1234321 commented on src/index.html
> +  <script type="text/javascript">
Instead of doing this, is it possible to use any node module?

2021-08-21 07:22 UTC, abhishek1234321 commented on src/app/qbo/dashboard/dashboard.component.html
> +            (click)="mapEmployeesEvent()">
`onMapEmployees` or some other better name, please read about the best convention for methods naming in Angular

also, change it everywhere in this PR

2021-08-23 06:08 UTC, labhvam5 commented on environment.localhost.template.ts
> -  hotjar_whitelist_url : 'HOTJAR WHITELIST URL',
since we are not using hotjar in development mode. Also is staging and prod we are simply using the hotjar_id variable only not the  hotjar_whitelist_url.

2021-08-23 10:14 UTC, abhishek1234321 commented on src/index.html
> +  <script type="text/javascript">
do not inject this on local?

2021-08-23 10:14 UTC, abhishek1234321 commented on src/app/qbo/qbo.component.ts
> +  setUserIdentity(email, properties) {
`email: string`

2021-08-23 10:14 UTC, abhishek1234321 commented on src/app/qbo/dashboard/dashboard.component.ts
> +  }
why are we passing it like this? could you not use ES6 default values in the method?

2021-08-23 10:30 UTC, labhvam5 commented on src/index.html
> +  <script type="text/javascript">
yes since we only need hotjar recording of prod users

2021-08-23 10:43 UTC, labhvam5 commented on src/app/qbo/dashboard/dashboard.component.ts
> +  }
was not aware of this feature.

2021-08-23 10:49 UTC, abhishek1234321 approved these changes

2021-08-23 10:49 UTC, abhishek1234321 commented on src/index.html
> +  <script type="text/javascript">
I was saying do the same for Segment too :D

2021-08-23 10:59 UTC, merged