splitting Reimbursable and CCC ExpenseGroup Settings
fylein/fyle-qbo-app pull request #104
Opened 2021-08-25 17:17 UTC by Sravanksk

2021-09-08 07:00 UTC, Shwetabhk commented on src/app/qbo/sync-export/sync/sync.component.ts
> +        } else if (element === 'expense_id') {
expense id is twice

2021-09-08 07:01 UTC, Shwetabhk commented on src/app/qbo/sync-export/sync/sync.component.ts
> +    if (that.expenseGroupSettings.reimbursable_export_date_type === 'spent_at') {
the date type resolution can be done with a common function for both reimbursable export type and ccc export type

2021-09-08 07:03 UTC, Shwetabhk commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +      let reimbursibleConfiguration = null;
`reimbursable` spelling is wrong

2021-09-08 07:04 UTC, Shwetabhk commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +        reimbursibleConfiguration = 'claim_number';
`reimbursable`

2021-09-08 07:04 UTC, Shwetabhk commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +        reimbursibleConfiguration = 'settlement_id';
reimbursable

2021-09-08 07:05 UTC, Shwetabhk commented on src/app/core/services/expense-groups.service.ts
> +  createExpenseGroupsSettings(reimbursibleExpensesGroupedBy: string[], cccExpensesGroupedBy: string[], expenseState: string[], reimbursableExportDateType: string, cccExportDateType: string): Observab
reimbursable spelling

2021-09-08 07:06 UTC, Shwetabhk commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
>        if (reimbursableFields.includes('claim_number')) {
The order is wrong here right?
It should be `Expense`then `Claim Number`then `Settlement Id`

2021-09-08 07:06 UTC, Shwetabhk commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +      if (cccFields.includes('expense_id')) {
The same order should be there for Reimbursable Expenses

2021-09-08 07:07 UTC, Shwetabhk commented on src/app/qbo/sync-export/sync/sync.component.ts
> +    if (that.expenseGroupSettings.ccc_export_date_type === 'spent_at') {
move to common function

2021-09-08 07:39 UTC, Sravanksk commented on src/app/qbo/sync-export/sync/sync.component.ts
> +    if (that.expenseGroupSettings.reimbursable_export_date_type === 'spent_at') {
this can be removed now, previously we used this `exportDateConfiguration` to show export date type in the main card, now we won't be showing that info in the card, so removing this part now

2021-09-08 09:52 UTC, ashwin1111 requested changes

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/core/services/expense-groups.service.ts
> -    cacheBusterObserver: expenseGroupSettingsCache$
please don't remove this :)

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/core/services/expense-groups.service.ts
> +  createExpenseGroupsSettings(reimbursibleExpensesGroupedBy: string[], cccExpensesGroupedBy: string[], expenseState: string[], reimbursableExportDateType: string, cccExportDateType: string): Observab
not fixed yet

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/core/services/expense-groups.service.ts
> +  createExpenseGroupsSettings(reimbursibleExpensesGroupedBy: string[], cccExpensesGroupedBy: string[], expenseState: string[], reimbursableExportDateType: string, cccExportDateType: string): Observab
pass the whole object from the component.
```
createExpenseGroupsSettings(expenseGroupsSettingsPayload: ExpenseGroupSetting): Observable<ExpenseGroupSetting> {. . .}

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +    const that = this;
`return this.workspaceGeneralSettings.corporate_credit_card_expenses_object;`

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.html
> +          <div class="dialog--group-label-left" *ngIf="showCCCGroups()">
Why are we checking ccc object availability for Reimbursable Expenses? Not getting this

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.html
> +        <mat-form-field floatLabel="always" appearance="outline" required [ngClass]="showCCCGroups()?'dialog--group-field-left':'dialog--group-field'">
Spacing, fix it everywhere
`showCCCGroups() ? 'dialog--group-field-left' : 'dialog--group-field'`

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.html
> +          <div class="dialog--group-label-left" *ngIf="showCCCGroups()">
okay, got it, we are not including reimbursable expense keyword incase if we have just reimburse exports. Correct me if I am wrong

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.html
> +            formControlName="cccExpenseGroupConfiguration" *ngIf="showCCCGroups()">
`*ngIf="showCCCGroups()` is not needed

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.html
> +            <mat-option value="current_date">
Can you put all the available options in an array in the component and loop over them? This is repeated at 2 places

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.html
> +          <mat-select placeholder="Choose Date when Exporting Expenses" formControlName="cccExportDate" *ngIf="showCCCGroups()">
`*ngIf="showCCCGroups()` is not needed

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.scss
> +    float:left;
: <space> everywhere

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +    this.expenseGroupsService.createExpenseGroupsSettings(reimbursableExpensesGroupedBy, cccExpensesGroupedBy, expenseState, reimbursableExportDateType, cccExportDateType).subscribe(response => {
pass as single object to `createExpenseGroupsSettings`

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +      if (reimbursableFields.includes('expense_id')) {
Do this in a separate function, same logic is duplicated twice.

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +    const cccExpensesGroupedBy = [that.importExpensesForm.value.cccExpenseGroupConfiguration];
if you do this `that.importExpensesForm.controls.cccExpenseGroupConfiguration.disable();`  won't work.
`.getRawValues()` or something similar to that should do.

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
>      that.getExpenseGroupSettings();
this should be inside `settingsService.getGeneralSettings()`

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/sync.component.ts
> +    that.expenseGroupSettings.corporate_credit_card_expense_group_fields.forEach(element => {
Do this in a separate function, same logic is duplicated twice.

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/sync.component.ts
> +  dialogWidth: string;
not needed

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/sync.component.ts
> +    that.dialogWidth = '450px';
Replace this everywhere.
`let dialogWidth = '450px';`

2021-09-08 09:52 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/sync.component.ts
>      const dialogRef = that.dialog.open(ExpenseGroupSettingsDialogComponent, {
all these logic should live inside `settingsService.getGeneralSettings()`

2021-09-08 09:54 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.scss
> +    float:left;
spacing

2021-09-08 11:58 UTC, Sravanksk commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +    const cccExpensesGroupedBy = [that.importExpensesForm.value.cccExpenseGroupConfiguration];
this is working `that.importExpensesForm.controls.cccExpenseGroupConfiguration.disable();`

2021-09-08 13:09 UTC, ashwin1111 commented on src/app/core/models/expense-group-setting.model.ts
> +  workspace?: number;
Shouldn't we send workspace every time?

2021-09-08 13:12 UTC, ashwin1111 commented on src/app/qbo/sync-export/sync/expense-group-settings-dialog/expense-group-settings-dialog.component.ts
> +  getFieldConfiguration(fieldType) {
`fieldType: string`

2021-12-10 08:40 UTC, NileshPant1999 approved these changes

2021-12-10 08:47 UTC, merged