showing qbo errors in the UI
fylein/fyle-qbo-app pull request #75
Opened 2021-06-29 07:01 UTC by NileshPant1999

2021-06-29 07:10 UTC, Sravanksk commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.html
> +</div>
new line

2021-06-29 07:10 UTC, Sravanksk commented on src/app/core/models/task.model.ts
> +  quickbooks_errors: QuickbookError[];
`quickbooks_errors: QuickbooksError[];`

2021-06-29 07:11 UTC, Sravanksk commented on src/app/core/models/quickbooks-error.model.ts
> +export type QuickbookError = {
`QuickbooksError`

2021-06-30 06:01 UTC, ashwin1111 commented on src/app/core/models/quickbooks-error.model.ts
> +
rm

2021-06-30 06:08 UTC, ashwin1111 requested changes

2021-06-30 06:08 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.html
> +  <zero-state message="This expense group has no Quickbooks Online errors"></zero-state>
this tab should be shown only when there are qbo errors

2021-06-30 06:08 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.ts
> +
rm

2021-06-30 06:08 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.ts
> +    that.taskService.getTasksByExpenseGroupId(that.expenseGroupId).subscribe((res: Task[]) => {
can you fix the same you did in other app? getTasksByExpenseGroupId should return just 1 task, fix it off it api as well as app.

2021-06-30 06:08 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.html
> +  <zero-state message="This expense group has no Quickbooks Online errors"></zero-state>
if that is the case, then why do you need a zero state?

2021-06-30 06:08 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/view-expense-group.component.html
> +      <a mat-tab-link *ngIf="showMappingErrors" (click)="changeState('MAPPING_ERRORS')" [active]="state==='MAPPING_ERRORS'">
`state === 'MAPPING_ERRORS'`

2021-06-30 06:08 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/view-expense-group.component.html
> +      <a mat-tab-link *ngIf="showQuickbooksErrors" (click)="changeState('QUICKBOOKS_ERRORS')" [active]="state==='QUICKBOOKS_ERRORS'">
spacing b/w ===

2021-06-30 06:08 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/view-expense-group.component.ts
> +        that.showMappingErrors = that.task.detail ? true : false;
We store success logs OR mapping errors in detail column. I assume that doesn't affect it, please test it out and confirm here.

2021-07-01 06:07 UTC, NileshPant1999 commented on src/app/qbo/expense-groups/view-expense-group/view-expense-group.component.ts
> +        that.showMappingErrors = that.task.detail ? true : false;
yes it is not affecting that.

2021-07-01 06:13 UTC, NileshPant1999 commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.html
> +  <zero-state message="This expense group has no Quickbooks Online errors"></zero-state>
yes true can remove this

2021-07-05 09:43 UTC, Sravanksk approved these changes

2021-07-06 07:35 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.html
> +  <zero-state message="This expense group has no Quickbooks Online errors"></zero-state>
please fix this

2021-07-06 07:35 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.ts
> +
fix this

2021-07-06 07:35 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/group-quickbooks-error/group-quickbooks-error.component.ts
> +    that.taskService.getTasksByExpenseGroupId(that.expenseGroupId).subscribe((res: Task[]) => {
fix

2021-07-06 07:36 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/view-expense-group.component.html
> +      <a mat-tab-link *ngIf="showMappingErrors" (click)="changeState('MAPPING_ERRORS')" [active]="state==='MAPPING_ERRORS'">
fix

2021-07-06 07:36 UTC, ashwin1111 commented on src/app/qbo/expense-groups/view-expense-group/view-expense-group.component.html
> +      <a mat-tab-link *ngIf="showQuickbooksErrors" (click)="changeState('QUICKBOOKS_ERRORS')" [active]="state==='QUICKBOOKS_ERRORS'">
fix

2021-07-06 07:51 UTC, ashwin1111 approved these changes

2021-07-06 09:15 UTC, Shwetabhk approved these changes

2021-07-19 07:31 UTC, merged