Improve mandatory fields visibility
fylein/fyle-qbo-app pull request #82
Opened 2021-07-20 10:24 UTC by NileshPant1999

2021-07-20 15:23 UTC, ashwin1111 requested changes

2021-07-20 15:23 UTC, ashwin1111 commented on src/app/shared/mandatory-field/mandatory-field.component.scss
> +}
new line

2021-07-21 18:05 UTC, NileshPant1999 commented on src/app/qbo/settings/schedule/schedule.component.ts
> -    if (that.form.valid) {
yes

2021-07-21 18:07 UTC, NileshPant1999 commented on src/app/qbo/settings/general-mappings/general-mappings.component.ts
> -    if (that.accountsPayableIsValid && that.bankAccountIsValid && that.cccAccountIsValid && that.vendorIsValid && that.billPaymentAccountIsValid) {
yes

2021-07-21 18:07 UTC, NileshPant1999 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
> -    if (that.generalSettingsForm.valid) {
yes

2021-07-22 06:10 UTC, ashwin1111 approved these changes

2021-07-22 06:22 UTC, Sravanksk approved these changes

2021-07-26 07:55 UTC, merged