Tax implementation Quickbooks Online
fylein/fyle-qbo-app pull request #99
Opened 2021-08-17 07:04 UTC by NileshPant1999

2021-09-15 14:41 UTC, ashwin1111 requested changes

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/core/models/general-setting.model.ts
> +  import_tax_codes?: boolean;
Why is this optional?

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/qbo/settings/configuration/expense-field-configuration/expense-field-configuration.component.ts
> +      setting => setting.source_field !== 'EMPLOYEE' && setting.source_field !== 'CATEGORY' && setting.source_field !== 'TAX_GROUP'
Do this in API

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
> +import { BillsService } from 'src/app/core/services/bills.service';
Why is this needed?

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
> +  constructor(private formBuilder: FormBuilder, private qbo: QboComponent, private billService: BillsService, private settingsService: SettingsService, private route: ActivatedRoute, private router:
same

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/core/services/mappings.service.ts
> +  getQBOTaxCodes(): Observable<MappingDestination[]> {
use default endpoint similar to NetSuite, no pointing in writing new methods since we'll clean all these methods.

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
> +      if (responses[2].country === 'US') {
Find a way to accommodate existing customers

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
>        that.isLoading = false;
this should be inside 209 block

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/qbo/settings/general-mappings/general-mappings.component.ts
> +        that.mappingsService.getQBOTaxCodes(),
use the generic method

2021-09-15 14:41 UTC, ashwin1111 commented on src/app/qbo/settings/generic-mappings/generic-mappings-dialog/generic-mappings-dialog.component.ts
> +      qboPromise = that.mappingsService.getQBOTaxCodes();
use generic method

2021-09-17 06:34 UTC, NileshPant1999 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
> +import { BillsService } from 'src/app/core/services/bills.service';
initially got it for company not needed now will remove

2021-09-20 04:36 UTC, ashwin1111 requested changes

2021-09-20 04:36 UTC, ashwin1111 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
> +      if (!responses[2].country) {
do this in a generic function, don't repeat same block of code more than once

2021-09-20 04:36 UTC, ashwin1111 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
> +    that.settingsService.getQBOCredentials(that.workspaceId).subscribe((res) => {
why is this written at 3 places

2021-09-20 04:38 UTC, NileshPant1999 commented on src/app/core/models/general-setting.model.ts
> +  import_tax_codes?: boolean;
it can be null for orgs that have not enabled it yet

2021-09-20 04:53 UTC, ashwin1111 commented on src/app/core/models/general-setting.model.ts
> +  import_tax_codes?: boolean;
This means, `GeneralSetting` can / cannot have `import_tax_codes` key which is not intended in our case. This would be always present.

2021-09-20 05:45 UTC, NileshPant1999 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.ts
> +    that.settingsService.getQBOCredentials(that.workspaceId).subscribe((res) => {
missed that removing from ng init

2021-09-20 14:39 UTC, ashwin1111 requested changes

2021-09-20 14:39 UTC, ashwin1111 commented on src/app/core/models/grouped-destination-attribute-model.ts
> +};
new line

2021-09-20 14:39 UTC, ashwin1111 commented on src/app/qbo/settings/general-mappings/general-mappings.component.ts
> +  return attributes;
Remove duplicates before returning here

2021-09-21 08:09 UTC, ashwin1111 approved these changes

2021-09-21 08:09 UTC, ashwin1111 commented on src/environments/environment.ts
> -  fyle_url: 'FYLE URL',
:)

2021-09-29 11:45 UTC, ashwin1111 commented on src/app/qbo/settings/configuration/general-configuration/general-configuration.component.html
> +      <mat-slide-toggle color="primary" class="schedule" *ngIf="qboCompanyCountry!=='US'" formControlName="importTaxCodes">
qboCompanyCountry !== 'US'
spacing

2021-09-29 13:32 UTC, merged